### ISSUE TITLE
CLI Error

### ISSUE THREAD

**Issue by blockanz** [hvqzao/report-ng#1]
Hi,

I am trying to use the CLI version of report-ng.  When I run the Windows version (.exe) I get an error stating: Unknown Scan Format.  I am using a Burp Pro 1.7.07 export.

This scan works perfectly well if I add into the GUI.

I have attached a picture of the error.

I have also tried this using the python version under windows (python 2.7).  There is a box that flashes up but it is so fast I can not see the output and it fails to create the report.

Can you advise what may be the cause and how to rectify.

Thanks

![report-ng-error](https://cloud.githubusercontent.com/assets/22645955/19128987/115407dc-8ba2-11e6-8dd6-bcb924b88744.png)

**Comment by hvqzao** [comment]
Hi blockanz,
To be honest - I've added CLI hoping that someone from my team will be interested in it, but this didn't happen. They prefer GUI with built-in yamled editor. Effectively, above means that this issue was not tested at all. Yet - I'll keep the problem in mind. When I'll be doing some fixing in the code I'll certainly look at your issue and provide some update here and hopefully in the code.

Anyways - in a meanwhile I recommend you to either stick to GUI frontend, or fetch all requirements and try to hack around `src/report.py` and `src/scan.py`. Below `if __name__ == '__main__':` line you should see my test cases used for debugging (and to generate scans and reports as well). I believe it is a perfect starting point to understand how report generating happens. This should let you easily fix the problem in CLI. It is probably some minor problem.

Also, what might be important, code should be newer than release build I've put on github. This usually means some fixes, but a chance that it will resolve CLI problems is rather small. Till next time!

**Comment by hvqzao** [comment]
CLI support was rewritten and tested (confirmed to work on Linux)
Release: https://github.com/hvqzao/report-ng/releases/tag/report-ng-0.9.5
